### ISSUE TITLE
ODF-lpOD_Helper-3.011 fails with bleadperl

### ISSUE THREAD

**Issue by andk** [jimav/ODF-lpOD_Helper#1]
Sample fail report: http://www.cpantesters.org/cpan/report/a64277fe-ff66-11ed-a696-d77c7733fdf8

Broken by smartmatch being deprecated.

**Comment by andk** [comment]
Meanwhile JIMAVERA/ODF-lpOD_Helper-5.011.tar.gz has been released, same result.

**Comment by jimav** [comment]
Hi, The problem (use of deprecated features) is not in this module, but in a module it uses.
The module names are similar, but  have different authors.

I believe one of the co-maintainers of ODF::lpOD (which has the problem) is working on it.  Meanwhile there is nothing I can do but wait for them to fix that module.

Best wishes,
-Jim
